follow = true

function init(self)
	msg.post("#camera", "acquire_camera_focus")
end


function update(self, dt)
	if follow == true then
		local window_width, window_height = window.get_size()
		go.set_position(vmath.vector3(-window_width / 2, -window_height / 2, 0), ".")
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("unfollow") then
		follow = false
		go.set_parent("camera", nil, true)
	end
end